### ISSUE TITLE
Polymorphic Relationships

### ISSUE THREAD

**Issue by rmammina** [redux-orm/redux-orm#118]
There's no way to dynamically set foreign key types if we are loading a polymorphic relationship.

For example, if I had a schema like the following
```
class User extends Model {}
User.modelName = "User";
User.fields = {
   id: attr(),
   name: attr(),
   email: attr(),
   devisable: // maps to either a customer or supplier model with fk()
}

class Customer extends Model {};
Customer.modelName = "Customer"
Customer.fields = {
   id: attr(),
   billing_address: attr(),
   orders: many("Orders", "customer")
}

class Supplier extends Model {};
Supplier.modelName = "Supplier"
Supplier.fields = {
   id: attr(),
   name: attr(),
   items: many("Items", "supplier")
}
```

How could I define a foreign key that lets me dynamically load the model, for instance, the user table had the following with a nested request:
```
User
======
id: integer
name: string
devisable_id: integer
devisable_type: string

/users/:id
{
   id: 4,
   name: "Bob Smith",
   email: "bob.smith@example.com",
   devisable_type: "Customer",
   devisable: {
       id: 16,
       billing_address: "1234 Cherry Street",
       orders: []
   }
}
```
So when I get the data back from users table, it might be a user with a customer or supplier result. 

What I'm getting at is, is there a way to dynamically set the foreign key for a model instance from another column?

**Comment by nealoke** [comment]
Why not just run a quick check in your reducer? 

**Customer reducer**
```
case RECEIVE_DEVISABLE:
	if (payload.devisable_type === 'Customer') {
		Customer.create({/* do stuff */})	
	}
break;
```

**Comment by rmammina** [comment]
That's fine when creating the appropriate related models, but the idea is I could use one field on the User model to point to different related models. Llke
```
session.User.hasId(4).devisable.update({billing_address: "100 Alleyway"})

or

session.User.hasId(5).devisable.update({name: "New supplier name"})
```

**Comment by nealoke** [comment]
@rmammina fairly sure you can do something like this:
`session.User.withId(5)[devisable].update(...)` also be sure that you use `withId` in stead of `hasId` when updating stuff as `hasId` returns a [boolean ](https://github.com/tommikaikkonen/redux-orm#model)

**Comment by haveyaseen** [comment]
Closing in favor of #177.
