### ISSUE TITLE
[RFC] Selector API Improvements

### ISSUE THREAD

**Issue by haveyaseen** [redux-orm/redux-orm#251]
## Current situation
Redux-ORM has amazing memoization capabilities that allow it to prevent irrelevant changes to unrelated data from causing our selectors to re-execute unnecessarily. After reflecting on selectors from a bottom-up perspective, I think the current approach is really well thought out. Separating `createSelector` from the `ORM` class is important to prevent users from importing reselect if they don't want to. Further, access to the entire memoized session makes selectors extremely flexible.

But composing selectors is still a hassle and does not come close to the conciseness that we really want. The biggest problem I have with the current way is that it's annoying to deal with input parameters (see also #71, #104, #218, #246 and https://stackoverflow.com/q/51305719). Just look at the complexity involved in a query that should be easy to understand:
```javascript
const publisherAverageRating = createSelector(
    orm,
    state => state.orm,
    (state, id) => id,
    ({ Publisher }, id) => (
        avg(
            Publisher.withId(id).movies.toModelArray()
                .map(movie => movie.rating)
        )
    ),
);
```
## Proposal
Users want a way to access model instances and their relationships directly, without manually dealing with arguments, sessions and memoization at all. This is generally important to spare them from bugs and unnecessary code. So here's my suggestion for a very simple API.

### All model instances selector
```javascript
const publishers = createSelector(orm, orm.Publisher);
publishers(state);
// ↳ Publisher.all().toRefArray()
```

#### With composition
```javascript
const publisherNames = createSelector(
    orm,
    orm.Publisher,
    (_, publishers) => publishers.map(publisher => publisher.name)
);
publisherNames(state);
// ↳ Publisher.all().toModelArray().map(publisher => publisher.name)
```
This one uses `toModelArray` because `orm.Publisher` is specified as an input selector.

### Single model instance selector
```javascript
const publisher = createSelector(orm, orm.Publisher);
publisher(state, 123);
// ↳ Publisher.withId(123).ref
```
Note that this definition is exactly equal to the one for all model instances.  It's just that an ID is passed here. Saves us code :tada: If this is undesirable for some reason (e.g. naming), then we could provide two methods, for instance `orm.Publisher.all` and `orm.Publisher.one`.
#### With composition
```javascript
class Publisher extends Model {
    // ...
   address = () => `${this.streetNumber} ${this.street}`;
}
const publisherAddress = createSelector(
    orm,
    orm.Publisher,
    (_, publisher) => publisher.address()
);
publisherAddress(state, 123);
// ↳ Publisher.withId(123).address()
```

### Model relationship selector
```javascript
const publisherMovies = createSelector(orm, orm.Publisher.movies);
publisherMovies(state, 123);
// ↳ Publisher.withId(123).movies.toRefArray()
```

#### With composition:
```javascript
const publisherAverageRating = createSelector(
    orm,
    orm.Publisher.movies,
    (_, movies) => avg(movies.map(movie => movie.rating))
);
publisherAverageRating(state, 123);
// ↳ avg(Publisher.withId(123).movies.toModelArray().map(movie => movie.rating))
```

### The ORM needs to know how to get its current state.
The typical selector for retrieving the ORM's state from our Redux store is `state => state.orm`. We should intentionally deprecate passing it to `createSelector` because it distorts reselect's mapping from input arguments to arguments of the output selector.

Instead we could add some magic to detect it, for example by having `ORM#getEmptyState()` pass some unique identifier to `db#getEmptyState()`. Alternatively we can accept an argument in the ORM constructor, as in `new ORM({ stateSelector: state => state.orm })`.
### The ORM needs to provide field descriptors.
Now, initially, I thought we could just pass `Publisher` etc. instead of `orm.Publisher` as we are still passing the `orm` instance as the first argument. However, the user's models are not connected to a session yet. In other words, they are designed to be totally independent from both the ORM and other models as well. And that is great because they're more reusable that way and because `createSelector` needs to "wrap" them in a session itself.

Unfortunately it also means that they don't automatically have those field descriptors which we can use to create input selectors. So we should make all of them available on the ORM instance during construction. An easier alternative would be to pass arrays of this form instead: `['Publisher', 'movies']`. That could prevent confusion with session bound models but it also looks ugly. A third option would be to extend `ORM#get()` with a second argument: `orm.get('Publisher', 'movies')`.
```javascript
const publisherAverageRating = createSelector(
    orm,
    orm.get('Publisher', 'movies'),
    (_, movies) => avg(movies.map(movie => movie.rating))
);
```
## Questions
- What kinds of queries would you use this for?
  - Is this flexible enough or would it constrain you too much?
  - Would you need more input parameters other than primary keys?
- Could we extend this to other queries, like `orm.Issue.filter(issue => issue.rating > 9000)`?
  - Especially interested in the opportunities of caching those selectors properly. Specifically, those selectors may require `Map`-based `keySelector`s à la re-reselect (`FlatMapCache`).
- Would this work in a chained way, things like `orm.Movie.genre.movies`?
- Would passing around arrays of primary keys be reasonable? An example:
`movieRatings = createSelector(orm, orm.Movie, (_, movie) => movie.rating)`.
  - If yes, should the output be an array of selector outputs or a map of PK to selector outputs?
That is, should `movieRatings(state, [12, 34])` be `[5.9, 7.2]` or `{12: 5.9, 34: 7.2}`?
  - Would this approach suffice to then do compositions like
`publisherRatings = createSelector(orm, orm.Publisher.movies, movieRatings)` and
`publisherAvgRating = createSelector(orm, publisherRatings, (_, r) => avg(r))`?
- Is it fine to include re-reselect as a dependency for everyone using `createSelector`?
---
cc @cyril94440, @talolard, @N3TC4T, @Aryk, @markerikson, @B-Reif, @plandem, @nealoke, @TimVanMourik, @ernsheong, @kirbydcool
Curious to hear your thoughts on this!

**Comment by ernsheong** [comment]
You shouldn't take my words so seriously, but I'm all for simplicity without compromising the use case.

I also hope that we can do away with `toModelArray()` before we can call any array operations. Maybe add those array methods to QuerySet and underlyingly execute the query when array method is called.

**Comment by haveyaseen** [comment]
That's great feedback, thank you :slightly_smiling_face: Simplicity is what this idea is all about, and I'd love to know which shortcuts others would need so that we can find an API that's both simple and abstract enough.

The problem you describe sounds like it's caused by an improper use of selectors rather than a missing feature. Are you by any chance returning model instances instead of references? Memoization will only work as intended if you access all relationships _within_ the selector, and not afterwards. Then those relationships should be marked as relevant/accessed and the selector should be re-run as soon as they change.

**Comment by ernsheong** [comment]
> Are you by any chance returning model instances instead of references?

Yes, I am.

I see the problem now then. Models are frozen in time, while ref objects still point to the source? My use case for passing models into the view is that my models do other things, and I can call model hierarchies in Rails-like fashion, e.g. `this.model.modelA.modelB`, which is very powerful. My selectors also stay very lean.

> Then those relationships should be marked as relevant/accessed

I see, I didn't see `markAccessed` etc. in the docs, until I dug into the API. I will have to play around with this.

I guess another feedback is just better example documentation. I've feel like I've just been guessing my way through redux-orm so far. A lot of hidden/legacy options.

**Comment by haveyaseen** [comment]
Yep. In the background, when you run a Redux-ORM selector, a session will be started and everything you access will be recorded until you return something. Whatever happens after that will be disregarded. Therefore your selectors aren't re-executed. `toModelArray()` copies all data from the refs (raw objects in the "database") over to instances of your `Model` class which is why they don't change automatically.

Obviously the intuitive way is exactly the way you did it and that only works _until_ you want to use selectors for performance reasons. The sad thing is that we cannot correctly memoize direct access with the way selectors work now. `markAccessed` is not needed by the way. Instead you need to move `model.modelA.modelB` into a selector. I realize that this is frustrating because now you need to change or add selectors _as well as_ change your frontend code to not use Redux-ORM models and relationship accessors. (I guess I had to do that years ago, too …)

For React I'm wondering if there is a way to start and stop sessions on-the-fly to allow direct access within the render phase. Sort of like a `connect` HOC for Redux-ORM that will start a session in `mapStateToProps` (like selectors typically would already) but instead of ending the session within `mapStateToProps` it would end it after rendering has completed. Maybe that's possible to accomplish with React hooks (or `componentDidUpdate` for that matter).

Selectors would still be necessary, though, because complex data transformations should not be performed inside of React components. This would bloat them up and weaken reusability.

**Comment by ernsheong** [comment]
Thanks for the quick response. That's a pain... For the record I am using LitElement, so I'm not tied up with React, but it's the same idea (re-render on model change) 

I suppose Rails could get away with it (model chaining) because the bloat sits in the server. I really wish we had that functionality in the browser too. 

Aite, sorry for hijacking the call for feedback on selectors.

**Comment by haveyaseen** [comment]
I appreciate you taking the time to give some honest feedback!

Regarding LitElement and React, it looks to me that they both expose lifecycle methods so there really shouldn't be a lot of differences. That is, if wrapping the render phase in a memoized session is actually possible in principle.

---

As for your feedback, I would like to make some additional points to further explain why I think the changes are still worthwhile. The magic is introduced on purpose to avoid writing the same code over and over again. Which code? Well, the selectors that `createSelector` returns by default are invalidated as soon as any input parameters have changed since the last time the selector has been run. Let's look at the `publisherAverageRating` example again:
```javascript
const publisherAverageRating = createSelector(
    orm,
    state => state.orm,
    (state, id) => id,
    ({ Publisher }, id) => (
        avg(
            Publisher.withId(id).movies.toModelArray()
                .map(movie => movie.rating)
        )
    ),
);
```
Now what happens if we want to compute the average rating for different publishers?
```javascript
publisherAverageRating(state, 1); // first time: need to execute
publisherAverageRating(state, 1); // same parameters: can be skipped
publisherAverageRating(state, 2); // different parameter: need to execute
publisherAverageRating(state, 1); // different parameter: need to execute
```
Note that the last call causes the selector to be re-executed, even if the state itself hasn't changed at all.   With `re-reselect` it's possible to create a different selector for each database row. Which is *always necessary* for optimizing Redux-ORM selectors. So we should implement this in some way using each model's primary key attribute (see https://github.com/tommikaikkonen/redux-orm/issues/246#issuecomment-475272434).

---

The `selectorFactory` idea is really good, especially for allowing customization. The concerns I have with it are two-fold:
- It introduces a separate step. Not a big deal, though, because the step of providing the `ORM` instance has to be performed and documented in all cases.
- It distorts the mapping of input selectors to output selector arguments. The arguments to our final selector (e.g. `session` and `id`) should directly have corresponding input selectors at the correct position (e.g. `orm` and `(state, id) => id`). Right now there is one excessive input selector. If we eliminated both we would have a missing input selector instead. I would propose just mapping any input selector that is an `ORM` instance to an argument containing the session.

**Comment by TimVanMourik** [comment]
Hi @haveyaseen,
Thanks for the proposal, I really appreciate the way in which you're trying to improve this software and your earlier help on my StackOverflow question. I'll try to answer the your questions from my user perspective. I'm quite a newbie to render cycles, memoization, and `redux-orm` under-the-hood, so although I tried to do some homework on all this I might be missing things here and there.

* The `Publisher.all().toModelArray().map(publisher => publisher.name)` has always seemed unnessarily verbose to me. So I appreciate the change to `(_, publishers) => publishers.map(publisher => publisher.name)` as it is quite intuitive what's going on.

### Single instance case
``` 
// current proposal:
const publisherMovies = createSelector(orm, orm.Publisher.movies);
publisherMovies(state, 123);
// ↳ Publisher.withId(123).movies.toRefArray()
```
* However, the single instance case is not necessarily intuitive. Sure, by convention you could pose that the second argument can be the id, but an API like {id: 123} is clearer. Now that kind of API implies support for other queries and I’m not sure if that’s desired or even possible. I suppose that’s an answer to your second question: yes, that type of filter would be quite empowering, but I don’t have the expertise to say if it’s even possible. 
```
const publisherMovies = createSelector(orm, orm.Publisher.movies);
publisherMovies(state, {id: 123});
// The following is not valid JavaScript, but just to convey the filter idea:
// ↳ Publisher.filter(id: 123).movies.toRefArray()
```

* Also, I feel it’s counter-intuitive that the id gets ‘inserted’ in `Publisher.movies` as 
`Publisher.withId(123).movies`.

* Your third question about chaining things like `orm.Movie.genre.movies` Would be useful, but could only work if there is an X-to-one relationship and a movie only has a single genre. So this kind of chaining would need to throw an error X-to-many relationships I guess. That might confuse the API as it’s not a general solution. 

* I tried to think about the answers for the last two questions, but I don’t think I’ve got anything relevant ideas to bring to the table here, sorry.

That’s my best shot at feedback to the proposal! Hopefully it’s useful and I’m happy to answer any more questions and will try to respond more timely next time!

**Comment by haveyaseen** [comment]
Hey @TimVanMourik, happy to see you taking the time to comment as well :tada: :smile: 

I think that I haven't made the motivation clear enough. Really this idea is about simplifying the most common use cases only. This proposal without the _model vs. ref_ distinction will essentially have the same flexibility as your desired API. Doing away with that distinction is a separate matter, at least in terms of the necessary code changes.

Of course the existing flexibility will remain, so everything that is possible right now will stay possible in the future as well! The main reason for implementing this is to make **complex** custom selector functions **easier to write**. Especially when it comes to resolving their dependencies (single model by ID, multiple models using an array of IDs, related models of a single model). The other purpose is to make selectors reusable as much as possible, both to (hopefully) reduce selector calls and to reduce boilerplate code.

If we can (and should) eventually remove the need for `toModelArray` (as @ernsheong suggested in #253) then your objections boil down to using `QuerySet#filter` directly and the point I initially made about `Map` based `keySelector`s like re-reselect's `FlatMapCache`. Maps accept objects as keys and can therefore be used to cache results by function or object reference. The problem with this is that the way you proposed (e.g. `{ id: 123 }`) will create a new object on each call, effectively always invalidating that cache and thus defeating the purpose of caching in the first place. So the better option for those cases would likely be selector composition and, if necessary, custom caching logic outside the scope of Redux-ORM.

**Comment by haveyaseen** [comment]
@ernsheong @TimVanMourik  @cstoneham @fgallinari @N3TC4T @noetix This is now ready with some slight changes! Please try out [v0.14.0-rc.0](https://github.com/redux-orm/redux-orm/releases/tag/v0.14.0-rc.0) :slightly_smiling_face:
