### ISSUE TITLE
Cannot read property 'items' of undefined when chaining selectors

### ISSUE THREAD

**Issue by michaelvbe** [redux-orm/redux-orm#256]
I'm trying to chain multiple selectors together (by passing them as argument), but get the following error:

```
Table.js:97 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at Table.accessIdList (Table.js:97)
    at Table.accessList (Table.js:101)
    at Table.query (Table.js:159)
    at query (Database.js:24)
    at Session.query (Session.js:121)
    at QuerySet._evaluate (QuerySet.js:238)
    at QuerySet.toModelArray (QuerySet.js:88)
    at Variant.js:18
	...
```

Top most selector (defined in Variant.js):
```js
export const getVariants = createSelector(
  orm,
  getModels,
  (session, models) => session.Variant
    .all()
    .toModelArray()
 })),
);
```

Dependency selector (defined in Model.js)
```js
export const getModels = createSelector(
  orm,
  (session) => session.Model
    .all()
    .toModelArray()
);
```

If i leave out `getModels` in the `getVariants` selector, it works perfectly.

This could also be a reselect issue but i'm not sure about that.

**Comment by haveyaseen** [comment]
Please try passing an additional input selector for retrieving the ORM's state slice as the second argument to `createSelector`, such as `state => state.orm` (wherever you put the output of `createReducer`):
```js
const ormState = state => state.orm;

export const getVariants = createSelector(
  orm,
  ormState,
  getModels,
  (session, models) => session.Variant
    .all()
    .toModelArray()
 })),
);

export const getModels = createSelector(
  orm,
  ormState,
  (session) => session.Model
    .all()
    .toModelArray()
);
```

**Comment by michaelvbe** [comment]
Hmm i was passing the ORM state directly because using an input selector would yield the same error.

Except it works now somehow.

Could it be a good idea to check if a state passed into createSelector is indeed a ORM managed tree?
