### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by Eddie-CooRo** [redux-orm/redux-orm#259]
Hi. after upgrading to version `0.14.0-rc.1` I have the following error:
*Can't find variable: Symbol*
After tracking the stack trace, I found the following line in the `constants.js` file:
`export var STATE_FLAG = Symbol('REDUX_ORM_STATE_FLAG');`
Now, I guess because I'm in the react-native environment, *Symbol* is not supported and therefore, an error gets thrown. I've installed *es6-symbol* polyfill. Then the same error gets thrown for `Reflect`, And I couldn't fix it yet, even by using `babel-polyfill`, I think maybe this behavior and its workaround should get documented ( if you can't eliminate the need for Symbol & Reflect or import the needed polyfills in the redux-orm code itself).

**Comment by Eddie-CooRo** [comment]
Ok, It fixed by adding the following imports to the first of *index.js* file:
```
import 'core-js/es6/symbol';
import 'core-js/fn/map';
import 'core-js/fn/set';
import 'core-js/fn/array/find';
import 'core-js/es6/reflect';
import 'core-js/fn/reflect/construct';
import 'core-js/fn/reflect/set-prototype-of';
```
But some wierd things started to happening. Now first time the selector runs, the session.Product is my model and everything is right, but the second time it runs, session.Product references to the model's actuall data. It's a object with `items`, `itemsById` and `meta` fields :sob:

**Comment by Eddie-CooRo** [comment]
Also, the bug disappears when I run the app with the debugger turned on (JS runs on chromes v8 instead of core-js)
So there is a problem with polyfills :cry:

**Comment by haveyaseen** [comment]
Maybe upgrading JavaScriptCore as suggested in https://github.com/mobxjs/mobx-react/issues/498#issuecomment-396182983 will work? I don't use React Native so I don't know if that's a viable solution for you.

> But some wierd things started to happening. Now first time the selector runs, the session.Product is my model and everything is right, but the second time it runs, session.Product references to the model's actuall data. It's a object with `items`, `itemsById` and `meta` fields :sob:

This sounds really strange. The objects containing `items` and `itemsById` are our Redux state slices created by `createReducer`. They should *never* be exposed to functions within `createSelector` unless you explicitly pass in a state selector (i.e. the function like `state => state.orm` that is now passed to `new ORM({ stateSelector })` instead). Are you still doing that by any chance?

**Comment by Eddie-CooRo** [comment]
> They should never be exposed to functions within createSelector unless you explicitly pass in a state selector (i.e. the function like state => state.orm that is now passed to new ORM({ stateSelector }) instead). Are you still doing that by any chance?

No, I didn't do that.
And as I said, when I turn on the debugger, everything works correctly. I'm somehow sure that the strange behavior is caused by polyfilling `Reflect` API.

**Comment by haveyaseen** [comment]
`Reflect` was introduced almost a year ago though, in #213 :thinking: 
This is likely related to `Symbol` not being available pre-ES6. If `Reflect` is not available it should have led to an error before. And even [core-js 2 supports most of `Symbol`](https://kangax.github.io/compat-table/es6/#babel6corejs2) indicating that you are not actually using core-js. Have you looked into https://github.com/react-native-community/jsc-android-buildscripts? Your descriptions seem to be in line with others' comments on the MobX issue:

> Turning on Debug JS Remotely fixed the issue for me.

> The default [JavaScriptCore] is from 2014 (!!) and doesn't support any modern features

> Oh I didn't know The default JavaScriptCore on Android is so old!!!

**Comment by Eddie-CooRo** [comment]
This bug fixed after migrating to the latest version of react-native (0.59.8) which always uses the newest version of js-core by default.
(It's nice to have a section about this issue in the documentation for the react native users)

**Comment by haveyaseen** [comment]
Great to hear! :smiley:
