### ISSUE TITLE
Opposite of `fk`

### ISSUE THREAD

**Issue by denis-n** [redux-orm/redux-orm#263]
Hi,

**Question 1**: how to define the the opposite of `fk`.

For example, I have a `User` and a `Pet` model. One `User` can have many `Pets`, but each `Pet` can have only one `User`.

The `Pet` will have a `fk('User')`.

When I load a `User` with many `Pets`, what is the correct way to declare that the `User` can have many `Pets`? This will make the schema more clear.

**Question 2:** what is the correct way to create the `User` in this case, so the `Pets` will be normalized as well?

**Comment by haveyaseen** [comment]
1. Simply replace `fk('User')` by `fk('User', 'pets')`. To prevent overriding the user id define it using a separate field name in the following way instead:
```javascript
Pet.fields = {
    // ...
    // replace user_id by whatever your JSON contains
    user_id: fk({
        to: 'User',
        as: 'user',
        relatedName: 'pets',
    }),
};
```
2. Create user instances without caring about their pets. If your API returns both user and pets at the same time, make sure to create both separately. If you're asking how to specify the foreign key relationship within the `User` model, you don't need to do that.

**Comment by denis-n** [comment]
The API returns hierarchical data, which I want to normalize.

**Comment by denis-n** [comment]
What if `User` model has a collection of `Pets`. 
I create `Pets` and create `Users`, but it looks like the user doesn't contain an array of id's for the pets.

**Comment by haveyaseen** [comment]
Normalization has to be done by hand for now. The user object itself won't expose an array of ids.

How exactly are you trying to retrieve the pets? If you're a bit more precise I might be able to tell you what's missing.

**Comment by denis-n** [comment]
The API returns a user and it has many pets.

First I create all the pets and get an array of their ids (`string[]`).

Second I create the user and assign the `ids` to created `User.pets` prop.

Is that a correct way to create a relationship between `User` and `Pets'?
Will I get the pets for a user by `user.pets` if I assign the pets in this way?

Will the `Pet.user` relationship work after this? I think that it should not work.
How can I make `Pet.user` relationship work? Assign the `id` of the user to `Pet.user`?

**Comment by denis-n** [comment]
Sorry, I only started to work with `redux-orm`.

**Comment by haveyaseen** [comment]
No worries, I understand if this is confusing. Especially because there's some magic involved here.

If you try to set `user.pets` you will get [an error](https://github.com/redux-orm/redux-orm/blob/2eb51fa2c1a523c75ca5cd6c2873a799b0c1f526/src/descriptors.js#L128), but looping over the pets and setting `pet.user = user` should work:
```js
const session = orm.session();
const petIds = [1, 3, 4, 8, 12];
const user = session.User.create({
    id: 1,
    name: 'Bob',
});
session.Pet
    .filter(pet => petIds.includes(pet.id))
    .toModelArray()
    .forEach(pet => pet.user = user);
```
Alternatively you can create the `Pet` instances with the user ID directly, if you know the user's ID upfront.

**Comment by denis-n** [comment]
Yes, I tried to set `user.pets` first and got an error.

So in this way I can set up `pet->user` relationship. What about `user->pets`, will it be created automatically if I setup `pet->user` relationship?

**Comment by haveyaseen** [comment]
No, the `user.pets` relationship will be setup automatically.

`user.pets = <anything>` will always throw an error (although I doubt there's a particular reason for this).
Once you set `pet.user = user` or `pet.user_id = user.id` you will receive all pets as a `QuerySet` when you type `user.pets`. How you can access this of course entirely depends on where you are doing this and what you're trying to achieve in the end. It should not be done and cannot easily be done in React components for example.

**Comment by denis-n** [comment]
Thank you, now I understand it.
