### ISSUE TITLE
@types/redux-orm updated to match 0.13.3

### ISSUE THREAD

**Issue by tomasz-zablocki** [redux-orm/redux-orm#264]
I've updated the @types/redux-orm declarations. The pr is in the merge queue and there's still time should anyone want to review or reject the changes.

_**A heads up for all users of current (*v0.9.4*) @types/redux-orm package**_

*Typings for 0.13.3 contain some breaking changes, so you probably want to stay on v0.9.4 - this  was a [hefty PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35609) and due to its volume it may not be 100% perfect. I'm sorry for any inconvenience this might cause - I'll be fixing any issues promptly. Thank you for your patience.*

In case there will be interest in using these typings, I'll provide a migration guide and TypeScript + redux-orm recipes for them (a bit of what was requested in #234 or #248). Till then, there's a batch of examples as [tests](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35609/files#diff-e24cacf8eb582bd2fb325e4db6b93ff2) in the @types/redux-orm package repository.

This is pretty much a scratch-made rewrite of redux-orm types. After numerous attempts on the matter, I believe that the new Model type annotations offer a good balance between the set of static type-safety+tooling/refactoring features and the amount of boilerplate and redundancy introduced when compared to pure JS application code. This is something I found to be the biggest challenge, considering the API and the dynamic nature of the Model classes.  

Currently there is quite a bit of TypeScript issues/feature requests regarding *static this* return type. These would be a gamechanger for redux-orm typing, reducing necessary type annotations and type complexity considerably.

I've also transferred and adjusted complete jsdocs, so using new type declarations should be  
IDE-friendly. The changelog containing major changes features and overall idea is in the [linked PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35609#issuecomment-497312877).

Best Regards

**Comment by tomasz-zablocki** [comment]
closing since it had been merged

**Comment by franferns** [comment]
I get this issue [https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36318](url) when i use types for complex types. How do i solve this ? Thanks
