### ISSUE TITLE
Specifying relations using Model classes

### ISSUE THREAD

**Issue by tomasz-zablocki** [redux-orm/redux-orm#265]
Would it be possible to introduce an alternative way of specifying relation targets, specifically by providing a `Model` class in place of a `modelName` string ?

The actual `modelName` would be extracted inside `RelationalField` constructor to keep the code intact after code mangling takes place.

Seems a bit more refactoring-friendly solution than strings. 

Additionally, combined with:

> Refactor many-many field declaration to allow forward/backward declaration at each Model:
> 
>     * implicit (almost like now, but with ability to declare relation at target model too) or
> 
>     * explicit (without any internal magic, cleaner code, easier to support), breaking changes

it would lay ground for a variety of TypeScript features to be introduced into current Redux-ORM typings.

**Comment by haveyaseen** [comment]
Sounds good! This adds possibilities for static code analysis. We should make sure to retain backwards compatibility, though, as using model classes may require importing them from other files.

**Comment by tomasz-zablocki** [comment]
@haveyaseen I've refactored related test cases, so that they import the Model classes defined in separate files. I've also moved the test cases to functional folder, which seemed to be a more appropriate place for them.

Please let me know if that change addressed the backwards compatibility concern you've mentioned.

**Comment by haveyaseen** [comment]
Thanks for being so responsive. However I think I didn't express myself very well. The PR looked fine before already as the backwards compatibility is ensured through previously existing tests. What I meant was simply that we should still be able to use strings to reference models. Importing in the tests shouldn't make a big difference in any case.

In fact, I don't think we should be locating the models directly under the `functional` folder. They have no relevance to other functional tests, so t's better to keep them directly in the test file or in a folder like `tests/functional/modelDeclarations/ReferencedModel.js`.

But we can do that later on. I'll go ahead and merge this :slightly_smiling_face:
