### ISSUE TITLE
"FieldInstaller is not a constructor"

### ISSUE THREAD

**Issue by perfect-ignorance** [redux-orm/redux-orm#272]
Getting the following error:

```
Uncaught TypeError: FieldInstaller is not a constructor
    at ORM._installField (ORM.js?aa4e:259)
    at eval (ORM.js?aa4e:224)
    at Array.forEach (<anonymous>)
    at eval (ORM.js?aa4e:222)
    at Array.forEach (<anonymous>)
    at ORM._setupModelPrototypes (ORM.js?aa4e:219)
    at ORM.getModelClasses (ORM.js?aa4e:160)
    at ORM.generateSchemaSpec (ORM.js?aa4e:166)
    at ORM.getDatabase (ORM.js?aa4e:182)
    at ORM.getEmptyState (ORM.js?aa4e:192)
```
Could be related to, but is not fixed by: [53](https://github.com/redux-orm/redux-orm/issues/53), [194](https://github.com/redux-orm/redux-orm/issues/194)

Reproducible using the minified bundle, and using the cdn version through a <script> tag.

I am not able to fix by using webpack's resolve.alias: `redux-orm: require.resolve('redux-orm/src')`. 
When using the alias, I get an object spread error.

We are on Babel 6, Webpack 3.

`babelrc`
```
{
    "presets": [
        "react",
        ["env", {
            "targets": {
                "browsers": ["last 2 major versions", "safari >= 8", "ie >= 11"]
            }
        }]
    ],
    "plugins": [
        ["transform-class-properties", { "spec": true }],
        ["transform-object-rest-spread"]
    ]
}
```
Have also tried a custom webpack rule when pointing to redux-orm/src:
```
const reduxOrm = {
    include: `${__dirname.split('/').slice(0, -1).join('/')}/node_modules/redux-orm/src`,
    test: jsRegex,
    use: [
        {
            loader: 'babel-loader',
            options: {
                babelrc: false,
                retainLines: true,
                cacheDirectory: true,
                comments: true,
                presets: [
                    require.resolve('babel-preset-react'),
                    [
                        require.resolve('babel-preset-env'),
                        {
                            "targets": {
                                "browsers": [
                                    "last 2 major versions",
                                ]
                            }
                        }
                    ],
                ],
                plugins: [
                    [
                        require.resolve('babel-plugin-transform-class-properties'),
                        { 'spec': true },
                    ],
                    [
                        require.resolve('babel-plugin-transform-object-rest-spread'),
                    ]
                ],
            }
        },
    ],
};
```

When using the above rules, I get the original error `FieldInstaller is not a constructor`.

Any help appreciated. I've tried all the hacks in 53 and 194. No luck.

**Comment by perfect-ignorance** [comment]
🤕 
So turns out, if you define a field to be a string in a model, you get the `FieldInstaller` error (because a string is not a class of course). 
And when you google that error you end up getting hits on all the class constructor issues. It's pretty easy to mistakenly think you have a transpilation issue.
For anyone else who face palms this one, make sure all the fields in your model are attr, fk, many, etc.

**Comment by haveyaseen** [comment]
Thanks @perfect-ignorance for reporting and for explaining the solution! We should catch this error upon schema generation / `ORM#register`.
