### ISSUE TITLE
0.14.0-rc.2 breaks integration with redux-persist

### ISSUE THREAD

**Issue by talolard** [redux-orm/redux-orm#273]
Hi,
I'm just testing out 0.14.0-rc.2. We use redux-persist to store the entire state, and when upgrading the site crashes. 
It seems that the newer version adds a **indexes** field to the models stored in state, and so when we load the state with redux-persist and that field isn't there everything crashes. 

I think the solution is outside the scope of the library, but this should definetly be noted in release notes. 
Likely solution is to write a migration in redux-persist that either creates empty indexes or resets the orm state that is saved and reloads it.

**Comment by haveyaseen** [comment]
Hi @talolard, yeah this is out-of-scope. Apparently redux-persist depends on your knowledge of the store's internals and as such it's impossible to reliably restore persisted state that was created by dependencies. v0.14.0 *is* a minor version bump below v1 so it should be considered breaking anyhow. But we can include a remark in the release notes for the final v0.14 release.

I'd advise against emptying `indexes`. That will lead to bugs.

Also note that when persisting you might run into problems with the new ES6 Symbol key at the top of each Redux-ORM state object. Hopefully redux-persist can handle this correctly.

https://github.com/redux-orm/redux-orm/blob/49e2d93d78e1aa25347fbd51c131e6b4ea4e8b22/src/constants.js#L12

https://github.com/redux-orm/redux-orm/blob/49e2d93d78e1aa25347fbd51c131e6b4ea4e8b22/src/db/Database.js#L10-L15
