### ISSUE TITLE
Redux Orm Memoization

### ISSUE THREAD

**Issue by denis-n** [redux-orm/redux-orm#286]
Hi,

My selectors return arrays of ids. I noticed that each time I edit an item of the array all of them are re-rendered.

I'm not using re-select because I was under the impression that redux-orm has memorization.
Should I use re-select or maybe I'm doing something wrong?

**Comment by haveyaseen** [comment]
Use reselect's `createSelector` for regular selectors, use Redux-ORM's `createSelector`for any selector that needs to access the ORM. Both provide memoization (Redux-ORM uses reselect and now even re-reselect under the hood).
