### ISSUE TITLE
Selector with memoization example

### ISSUE THREAD

**Issue by denis-n** [redux-orm/redux-orm#287]
Hi,

The example from documentation is confusing.

![image](https://user-images.githubusercontent.com/4423231/65568544-f1524300-df62-11e9-9bd3-f07626cec66a.png)

Questions: 
1) how to write a memoized selector which accepts an argument, for example, all Authors by country code
2) what is `dbStateSelector` in example above?

Thank you

**Comment by markerikson** [comment]
`dbStateSelector` is the function shown a couple lines earlier:

`const dbStateSelector = state => state.db`

The Redux-ORM `createSelector` function is a wrapper around the Reselect library.

I showed examples of how to use Reselect here:

https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/

So, in this example, I _think_ this should work:

```js
const selectDbState = state => state.db;
const selectItemId = (state, itemId) => itemId);

const selectAuthorById = createSelector(
    orm,
    selectDbState,
    selectItemId,
    (session, itemId) => {
        // use the session and the item ID value to retrieve and return something useful
    }
);
```

**Comment by denis-n** [comment]
How will `selectAuthorById` can be used?

`selectAuthorById(state, 1)`  or `selectAuthorById(state.orm, 1)`?

Is `const selectDbState = state => state.db;` always returning `state.db`?

**Comment by denis-n** [comment]
The following selector returns an array of ids.

Is it memoized?

```
export const workflowRunToDoSelector = (state: IAppState): string[] => {
    const selector = createSelector(
        orm,
        session => {
            return session.WorkflowRun.all()
                .filter(
                    (x: IWorkflowRun) =>
                        x.dynamicStatus === WorkflowRunDynamicStatus.Behind,
                )
                .toModelArray()
                .map((x: IWorkflowRun) => x.id);
        },
    );

    return selector(state.ormEntities);
};
```

**Comment by denis-n** [comment]
Each id from this array is passed to edit component.
Whenever any particular item is edited - everything is re-rendered.

Each time the redux state is updated (for example, isLoading property changes it's value)-> `mapToProps `is called, the selector in `mapToProps `is returning an array of ids and all edit components are re-rendered.

**Comment by denis-n** [comment]
I have an idea, but I'm not sure if it' is correct.

For example, this `mapToProps` code:

```
const mapToProps = (appState: IAppState): IStateProps => {
    const doneTodayWorkflowRuns = workflowRunDoneTodaySelector(appState);
    const doneEarlierWorkflowRuns = workflowRunDoneEarlierTodaySelector(
        appState,
    );
    const toDoWorkflowRuns = workflowRunToDoSelector(appState);

    return {
        isLoading: appState.workViewState.isLoading,
        allStatuses: appState.workflowRunViewState.allDynamicStatusesForWork,
        doneTodayWorkflowRuns,
        doneEarlierWorkflowRuns,
        toDoWorkflowRuns,
    };
};
```

All of the result's properties, except `isLoading` are arrays. What is wrong here?

**Comment by haveyaseen** [comment]
@denis-n Which version of Redux-ORM are you using? v0.14.0 has been released 2 days ago and simplifies writing some types of selectors. The documentation you posted above is for earlier versions, though. I'll try to answer your questions all at once.

#### What is `dbStateSelector`?

It's a function that will return your ORM state when given a Redux state tree. When you call Redux's `createStore` to set up your reducers, you give Redux a key under which to store the result of `createReducer(orm)`. Use this key to retrieve the ORM branch. In your case the correct ORM state selector should be `state => state.ormEntities`.

In versions before v0.14 you had to pass `orm` as the first argument to `createSelector` and `state => state.ormEntities` as the second argument. In v0.14 the ORM state selector needs to be passed to the `ORM` constructor once instead:

```diff
-const orm = new ORM();
+const orm = new ORM({
+  stateSelector: state => state.ormEntities,
+});

-const someSelector = createSelector(orm, state => state.orm, …);
+const someSelector = createSelector(orm, …);
```

`orm` could be something else instead. Please see the [latest docs on selectors](https://redux-orm.github.io/redux-orm/basics/selectors) for more information.

#### Is `workflowRunToDoSelector` memoized?

Not really. The problem is that you are creating a new selector function each time you call `workFlowRunToDoSelector` when you run this line `const selector = createSelector(…)`. Never call `createSelector` from within another selector. The correct way would be as follows.
```js
export const workflowRunToDoSelector = (state: IAppState): string[] => createSelector(
    orm,
    session => {
        return session.WorkflowRun.all()
            .filter(
                (x: IWorkflowRun) =>
                    x.dynamicStatus === WorkflowRunDynamicStatus.Behind,
            )
            .orderBy((x: IWorkflowRun) => x.startDate, "desc")
            .toModelArray()
            .map((x: IWorkflowRun) => x.id);
    },
);
```

The same goes for `selectAuthorById`, call it like this: `selectAuthorById(state, 1)` and have Redux-ORM take care of the rest. However, the v0.14 way to write it would  simply be:
```js
const authors = createSelector(orm.Author);
authors(state);             // array of all authors
authors(state, 1);          // author with ID 1
authors(state, [1, 2, 3]);  // array of authors with ID 1, 2 and 3
```
#### All of the result's properties, except isLoading are arrays. What is wrong here?

`workflowRunToDoSelector` returns an array so it's not surprising that `const toDoWorkflowRuns = workflowRunToDoSelector(appState);` is an array as well. Can't speak for the other selectors as I don't know what they look like.

**Comment by denis-n** [comment]
Is this line returning the entity from orm or ref of that entity?

`movies(state, 1);          // movie with ID 1`

https://redux-orm.github.io/redux-orm/basics/selectors#argument-types

**Comment by haveyaseen** [comment]
> Is this line returning the entity from orm or ref of that entity?
> 
> `movies(state, 1); // movie with ID 1`
> 
> https://redux-orm.github.io/redux-orm/basics/selectors#argument-types

It's a reference to the first movie, i.e. the exact object that was stored. See also https://redux-orm.github.io/redux-orm/api/module_redux#createselectorargs-function. As a general rule remember that selectors should never return model instances.

**Comment by denis-n** [comment]
Something is wrong with this selector.
It's called on each Redux state update (not related to redux-orm):

```
export const testSelector = createSelector(
    orm,
    (state: any, workflowRunId: string) => workflowRunId,
    (session, workflowRunId) => {
        const stepInstances = session.StepInstance.all()
            .filter(
                (x: IStepInstance) =>
                    x.workflowRunId === workflowRunId &&
                    x.completedAt !== undefined,
            )
            .toRefArray();

        if (stepInstances.length > 0) {
            return stepInstances.map(x => x.id);
        }
    },
);
```

I'm using latest Redux-orm version with modified typescript definitions for version 0.9 :)

Can you please check if there is anything wrong with this selector?

**Comment by denis-n** [comment]
I found the answer here: https://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/

**Comment by haveyaseen** [comment]
Would you mind posting the relevant knowledge or code, just in case anyone else stumbles upon the problem?

**Comment by denis-n** [comment]
I will copy the code from that article:

```
const makeUniqueSelectorInstance = () => createSelector(
    [selectItems, selectItemId],
    (items, itemId) => items[itemId]
);    


const makeMapState = (state) => {
    const selectItemForThisComponent = makeUniqueSelectorInstance();

    return function realMapState(state, ownProps) {
        const item = selectItemForThisComponent(state, ownProps.itemId);

        return {item};
    }
};

export default connect(makeMapState)(SomeComponent);
```

Explanation: Reselect only memoizes on the most recent inputs (ie, it has a cache size of 1)
It means that this code will not memoize correctly: 
```
// first instance
selectItemForThisComponent(state, 1);
// second instance
selectItemForThisComponent(state, 2);
```

To make it work, we need to rewrite mapStateToProps, it should return a "factory function" (check the first code snippet in this post)

**Comment by haveyaseen** [comment]
Alright :slightly_smiling_face:  In that case it can be written as follows if you're using v0.14, avoiding all the factory hassle:
```js

export const testSelector = createSelector(
    orm.WorkflowRun.stepInstances,
    (instances) => {
        const toBeCompleted = instances.filter(x => x.completedAt !== undefined);
        if (toBeCompleted.length) {
            return toBeCompleted.map(x => x.id);
        }
    },
};
```
Of course this assumes that you have created a WorkflowRun model and a foreign key field on `StepInstance.workflowRunId` with a `reverseName` of `stepInstances`.

**Comment by denis-n** [comment]
Unfortunately it didn't worked for me.

Maybe because I'm using typescript definitions for version 0.9 :(
