### ISSUE TITLE
Use with redux-persist

### ISSUE THREAD

**Issue by CevaComic** [redux-orm/redux-orm#288]
I would like to know if I can use redux-orm with redux-persist.
I have tried and I always get : 

TypeError: undefined is not an object (evaluating 'session.Friend.all')

I mention that the error is in the selector where i try to retrive all friends and messages data.
It works perfectly if I remove 'orm' from whitelist in redux-persist config

Here is my persistConfig: 

```
const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['login','orm'] // remove orm and works fine
}
```

Selector : 

```

export const getMessages = createSelector(
    schema,
    session => {
        return session.Friend.all().toModelArray().map(friend => {
            const { ref } = friend
            return {
                ...ref,
                messages: friend.messages.toRefArray().map(message => { 
					return { message: message.message, status: message.status }
				}),
            }
        })
    }
)
```

Or is there other way to save a session with all data ?

**Comment by haveyaseen** [comment]
@CevaComic Please post the whole backtrace of the error (where does `TypeError: undefined is not an object` throw exactly?) as well as any other information that could help find the underlying problem. Surely we want to allow storing the Redux-ORM state in localStorage/sessionStorage if we can reasonably do that. It would be nice to have a [CodeSandbox](https://codesandbox.io/) reproducing the issue as I have been unable to cause an error so far.

**Comment by lehovec** [comment]
@CevaComic You must set you persistConfig property stateReconciler to autoMergeLevel2.
Like that:
```
import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2'

const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['login','orm'] // remove orm and works fine,
  stateReconciler: autoMergeLevel2,
}
```
redux-orm add custom Symbol to store, but redux-persist merge only to one level by default. So when you use autoMergeLevel2, that redux-orm Symbol is merged and lib start working.

**Comment by CevaComic** [comment]
@lehovec , I didn't managed to make it work that way, but still I found a solution , maybe not the best : 

```
export const getMessages = createSelector(
    schema,
    session => {
        const session = schema.session(state.orm) // <--- added this inside selector
        return session.Friend.all().toModelArray().map(friend => {
            const { ref } = friend
            return {
                ...ref,
                messages: friend.messages.toRefArray().map(message => { 
					return { message: message.message, status: message.status }
				}),
            }
        })
    }
)
```

Thank you all for the answers
