### ISSUE TITLE
Map over collections using .map()

### ISSUE THREAD

**Issue by denis-n** [redux-orm/redux-orm#292]
Can you please write an example how this code is working the old way?

https://redux-orm.github.io/redux-orm/basics/selectors#map-over-collections-using-map

```
const bookAuthors = createSelector(orm.Book.authors);
const genreAuthors = createSelector(
    orm.Genre.books.map(bookAuthors)
);
```

I don't understand what is happening there.

The `.map()` method is an `ES6 `method, not a method of `redux-orm`?

**Comment by haveyaseen** [comment]
`map()` is a Redux-ORM method which returns a selector. It basically calls `bookAuthors(state, book.id)` for each book in `genre.books`. For simplicity's sake let's assume that books are stored using their title as the primary key.
```js
bookAuthors(state, 'The Adventures of Huckleberry Finn'); // ['Mark Twain']
bookAuthors(state, 'The Portrait of a Lady'); // ['Henry James']
```
So for each book, `genreAuthors` will call `bookAuthors` to find out its authors. It then returns a two-dimensional list of authors of books:
```js
genreAuthors(state, 'Realism'); // [ ['Mark Twain'], ['Henry James'] ];
```

**Comment by haveyaseen** [comment]
Maybe a better example would be genreTitles which is a little easier to understand:
```js
const genreTitles = createSelector(
    orm.Genre.books.map(orm.Book.title)
);
genreTitles(state, 'Realism');
// ['The Adventures of Huckleberry Finn', 'The Portrait of a Lady'];
```

**Comment by denis-n** [comment]
Thank you.

I was asking about the `map `method because in docs it's deprecated so it's confusing.

https://redux-orm.github.io/redux-orm/api/QuerySet#queryset+map

**Comment by denis-n** [comment]
Can I get all authors and their books and author address in one line?

Will it work?

```
const authorsSelector = createSelector(
    orm.Authors.map(orm.Books).map(orm.Address)
);
```

**Comment by haveyaseen** [comment]
It has nothing to do with the `QuerySet` class. This is purely related to the new selector syntax which is a separate abstraction.

Chaining after collections should work like this:
```js
const authorsSelector = createSelector(
    orm.Author.books.map(orm.Book.address)
);
```
The `map` function on a selector spec (the things that begin with `orm.<ModelName>`) receives either another selector spec or a selector function. The above is equivalent to:
```js
const authorsSelector = createSelector(
    orm.Author.books.map(
        createSelector(orm.Book.address)
    )
);
```

**Comment by haveyaseen** [comment]
Maybe I got you wrong. If the address is stored within author you need to provide a custom result function:
```js
const authorsSelector = createSelector(
    orm.Author.books,
    orm.Author.address,
    (books, address) => ({ books, address })
);
authorsSelector(state, 1);
/*
[
    {
        books: [
            { id: 1, title: 'The Portrait of a Lady}
        ],
        address: '529 College St. Lapeer, MI 48446'
    }
]
*/
```
See also https://github.com/redux-orm/redux-orm/issues/269#issuecomment-508285450.

Of course this gets more complicated if `authorsSelector` will be called without arguments or with an array of primary keys. See #282 for that.

**Comment by denis-n** [comment]
What if I want the author, his books and address?
Should it be like this?

```
const authorsSelector = createSelector(
   orm.Author,
    orm.Author.books,
    orm.Author.address,
    (**author**, books, address) => ({ **{...author}**, books, address })
);
```

**Comment by haveyaseen** [comment]
Yes, almost.
```js
const authorsSelector = createSelector(
    orm.Author,
    orm.Author.books,
    orm.Author.address,
    (author, books, address) => ({ ...author, books, address })
);
```

**Comment by denis-n** [comment]
Oh, I completely forgot that usually it's better to have separate selectors.

So while this code is working, I hope I will never used it)

Also, where can I read more about the `map `and `exclude `methods?

**Comment by haveyaseen** [comment]
The `map` code is here: https://github.com/redux-orm/redux-orm/blob/db1f15d22c9890d236e57a53bb4afa2d5ce40dfc/src/selectors/MapSelectorSpec.js

`QuerySet#exclude` is documented here: https://redux-orm.github.io/redux-orm/api/QuerySet#excludelookupobj-queryset

**Comment by denis-n** [comment]
Thank you.

I want to re-write the [redux-orm primer](https://github.com/tommikaikkonen/redux-orm-primer), but I don't have time now.
