### ISSUE TITLE
orderBy in descending order doesn't work

### ISSUE THREAD

**Issue by denis-n** [redux-orm/redux-orm#309]
Redux-orm version: 0.14
Typescript definitions for version 0.9

I noticed that this code doesn't work correctly after updating to version 0.14:
`.orderBy((x: IWorkflowRun) => x.startDate, "desc")`

but this worked:
`.orderBy((x: IWorkflowRun) => x.startDate, false)`

Here is the link to documentation:
https://redux-orm.github.io/redux-orm/api/QuerySet#orderbyiteratees-orders-queryset

I'm not sure if there is something wrong with my code or `orderBy` only accepts boolean values instead of strings.

**Comment by tomasz-zablocki** [comment]
Looks like a bug, which I thought had been fixed already. I'll give it a go today.

**Comment by denis-n** [comment]
I want to specify that the typescript definitions are the old version: 0.9
