### ISSUE TITLE
`STATE_FLAG` doesn't serialize

### ISSUE THREAD

**Issue by kirbydcool** [redux-orm/redux-orm#320]
Javascript symbols as object keys get ignored by `JSON.stringify`, so this causes the `STATE_FLAG` to be missing when rehydrating a store. This causes weird errors in selectors because the `orm` state isn't resolved to a session here https://github.com/redux-orm/redux-orm/blob/a352c21b7902b9aae319a9c3f71bd7e495f6bfd5/src/memoize.js#L164.

This breaks some common setups like server side rendering and redux-persist and is probably the root cause of https://github.com/redux-orm/redux-orm/issues/288

A quick workaround here would be to just use a string for `STATE_FLAG` instead of a symbol.

Edit: @haveyaseen Also, I'm happy to do the pr for this if you think using a string is the right solution (or whatever we decide).

Edit 2: Opened a pr for the proposed solution since it was quick https://github.com/redux-orm/redux-orm/pull/321

**Comment by kirbydcool** [comment]
I mostly used `JSON.stringify` because that's the example redux uses in their docs https://redux.js.org/recipes/server-rendering#inject-initial-component-html-and-state. And I think that's pretty typical for server rendering redux, although I don't have a ton of experience here.

I think it's a good idea to avoid making the the user customize do custom deserialization for their use case:
- Redux advocates that all state properties should be serializable https://redux.js.org/recipes/server-rendering#inject-initial-component-html-and-state
- There's a lot of possible serialization use cases that may or may not have good hooks to add custom deserialization code
- Exposing `Symbol('REDUX_ORM_FLAG')` as part of the public api seems inflexible and may lead to a required breaking change later on

That's interesting that jsdom `localStorage` seems to work with symbols! I'll take a look at your test case.

**Comment by kirbydcool** [comment]
I managed to get the test failing with some tweaking https://github.com/redux-orm/redux-orm/pull/322

**Comment by haveyaseen** [comment]
Thank you, that was really insightful :slightly_smiling_face:  I'll get that merged and the string change as well.

**Comment by kirbydcool** [comment]
@haveyaseen Awesome. Thanks for the the quick turn around! When do you think this will make it to a release?

**Comment by haveyaseen** [comment]
@kirbydcool Finally got around to releasing this (v0.15.0). Thanks again for your efforts!

**Comment by kirbydcool** [comment]
Great. Thanks!
