### ISSUE TITLE
Failed to resolve the current ORM database state. Please pass an object to the...

### ISSUE THREAD

**Issue by vedtam** [redux-orm/redux-orm#331]
Hi,

First, thanks for this great tool, I have really high hopes for it :)

After absorbing all the docs, tests, etc., I'm still unable to figure out why when trying to add my first selector, the orm throws:

`Failed to resolve the current ORM database state. Please pass an object to the ORM constructor that specifies a stateSelector function.`

For testing, I moved the selector all the way up to `orm`:

```
import { ORM, createSelector } from '/web_modules/redux-orm.js';
import { Channel } from './Channel.js';

const orm = new ORM();
orm.register(Channel);

const dbStateSelector = (state) => state.entities;

export const channelStories = createSelector(
  orm,
  dbStateSelector,
  (session) => console.log(session)
);

export { orm };
```

I tried to check out the state object to be sure:
```
export const channelStories = state => console.log(state.entities);
```

this seems to yield the state just fine:

![Screen Shot 2019-10-10 at 23 55 10](https://user-images.githubusercontent.com/4981592/66605816-753e3900-ebb9-11e9-948d-965e0b4a6d53.png)

Any suggestions?
Thanks!

**Comment by haveyaseen** [comment]
Please see https://redux-orm.github.io/redux-orm/basics/selectors.

```diff
-const orm = new ORM();
+const orm = new ORM({
+    stateSelector: state => state.entities,
+});
```

```diff
 export const channelStories = createSelector(
   orm,
-  dbStateSelector,
   (session) => console.log(session)
 );
```

**Comment by vedtam** [comment]
@haveyaseen Thanks, you'r great! Now I can run: `moviePublisher(state, [2]); ` as well, weee!

However, the docs state:

![Screen Shot 2019-10-11 at 00 29 26](https://user-images.githubusercontent.com/4981592/66608105-5db57f00-ebbe-11e9-9de6-d79e80a80548.png)

This is kinda confusing :(

Thanks!

**Comment by haveyaseen** [comment]
@vedtam Thank you, I updated the README accordingly :slightly_smiling_face:

**Comment by vedtam** [comment]
Btw, with the new method, TS types throw:

![Screen Shot 2019-10-11 at 08 32 55](https://user-images.githubusercontent.com/4981592/66629790-7b5d0580-ec0b-11e9-848f-097665f06bc1.png)

A temp fix could be (I'm not a TS ninja unfortunately to fix this properly):

![Screen Shot 2019-10-11 at 09 41 10](https://user-images.githubusercontent.com/4981592/66629816-8879f480-ec0b-11e9-8d52-6cb290407931.png)

**Comment by vedtam** [comment]
@haveyaseen please forgive me bugging you but with your suggested way of adding the `stateSelector ` to the ORM constructor something doesn't add up when dealing with selectors.

Naturally, I would consume an `ormCreateSelector` like this:

```
//in main.js:
async stateChanged(state: RootState) {
   //passes `RootState`
    this.channels = channelsSelector(state);
}

//in selectors.js

//exepts `ORM state` as first argument
export const channelsSelector = ormCreateSelector(
  orm,
  (session) => session.Channel.count()
);
```
which results in:
![Screen Shot 2019-10-11 at 11 05 16](https://user-images.githubusercontent.com/4981592/66635032-07c0f580-ec17-11e9-99f6-d9b0ca174369.png)

The app surely will run without issues cuz of how `ORM({stateSelector: ...})` resolves the slice, but this is not as the logic implies.
