### ISSUE TITLE
A ref returned model after selector can directly mutate a state

### ISSUE THREAD

**Issue by meltyshev** [redux-orm/redux-orm#340]
Hi, I have an issue with a returned value after a selector so you can mutate a state directly. Should a ref property return a deep clone of an object or may I miss something? Currently, I use custom wrapper for createSelector as a workaround for deep clone everything.

Reproduced it here: https://codesandbox.io/s/redux-orm340-gv7wd

Thank you!

**Comment by markerikson** [comment]
No, the point of a Redux-ORM "ref" is that it literally is the actual piece of data in the state, in the same way that calling `store.getState()` for the Redux store gives you an actual reference to the current store state value.

Don't mutate that result :)

**Comment by meltyshev** [comment]
Yeah, you are right! I thought that createSelector caches result by its params, so deep clone inside it doesn't cause any performance problems.

**Comment by meltyshev** [comment]
I just confused that data returned by the memoized selector has direct access to state which can produce some bugs, also there are no warnings in dev environment about this. Thank you!
