### ISSUE TITLE
Cannot set property idAttribute of function Model(props) {     this._initFields(props);   } which has only a getter

### ISSUE THREAD

**Issue by usmaniqbal998** [redux-orm/redux-orm#341]
Following is my redux orm model 

```
import { Model, attr } from "redux-orm";
import orm from "../orm";

class Authors extends Model {
  //static reducers method to perform action
  static reducer(action, Authors, session) {
    switch (action.type) {
      case "ADD_AUTHOR":
        Authors.create(action.payload);
        break;
    }
  }
}
Authors.modelName = "Authors";
Authors.backend = {
  idAttribute: "author_name"
};

Authors.fields = {
  author_id: attr(),
  author_name: attr(),
  author_email: attr(),
  author_phone_no: attr()
};
//console.log(orm);
//console.log("Idattr", Authors.idAttribute);

export default Authors;
```
this piece of code : Authors.backend = {
  idAttribute: "author_name"
};
i am using to add a custom id attribute on my redux authors state table but it gives me an error saying  

> Cannot set property idAttribute of function Model(props) {     this._initFields(props);   } which has only a getter

how can i set my custom idattributes in redux orm state table ? like we do in databases setting our own primary key for a table instad of using numerical auto generated keys

**Comment by haveyaseen** [comment]
`Authors.idAttribute = "author_name";`

**Comment by haveyaseen** [comment]
That's interesting, some parts of the code refer to setting `Model.options`, others set `Model.idAttribute` directly. Tables are created using `Model.tableOptions()` which essentially returns `Model.options` (or `Model.backend` but that should warn you of a deprecation). You might need to set both.

**Comment by usmaniqbal998** [comment]
it worked . actually the problem was with the "Model.backend" deprecations , with "Model.options" it worked . But it should be showing that Model.backend is deprecated message instead of throwing an error

**Comment by haveyaseen** [comment]
Great to hear. `Model.idAttribute` cannot be set directly as it is a getter property:
https://github.com/redux-orm/redux-orm/blob/7ca651ca2cc1413bdff0706236297890d0e4e14c/src/Model.js#L181
This needs to be changed in the docs.

**Comment by ernsheong** [comment]
Overriding the static getter direction also doesn't seem to work?

```js
static get idAttribute() {
  return "linkKey";
}
```

**Comment by guyjacks** [comment]
I'm still getting this error when I try `Book.idAttribute = 'pk'`.  

Should I be using the following instead?

`Book.options = {
  idAttribute: "pk",
};`
