### ISSUE TITLE
Reusability and Generalization with Redux-ORM

### ISSUE THREAD

**Issue by mbrahimi617** [redux-orm/redux-orm#417]
So I have an data table application in which there are several sections containing data. For example, I have an assets section with Table model instances and Item model instances. In my firmware section for example, I have Table model instances with Item model instances and another Info model foreign keyed to the Item model. My question is how do I make this extensible such that I can reuse the models for all of my sections?

All of my sections have a Table model and Item model but others can also have other additional models as seen in the case of my firmware section. My problem is when I delete table with ID 1 for example, how will I designate the reducer to respond only in a particular section? I want to basically isolate the ORM generated reducer on a section-level basis because each section has its own API and thus there will be multiple tables with ID 1 across different sections.

**Comment by haveyaseen** [comment]
Real polymorphism is still an unsolved problem (see #177). To achieve [single table inheritance](https://en.wikipedia.org/wiki/Single_Table_Inheritance) as in
```js
Table.fields = {
    id: attr(),
    section: attr(),
};
```
we would need the ability to specify multiple columns as a primary key (see #161). Another way would be to add a surrogate key that maps to non-unique ones. So you'd have
```js
Table.fields = {
    id: attr(),
    section: attr(),
    surrogateId: attr(),
};
Table.idAttribute = "surrogateId";
```
with possible instances being
```js
{ id: 1, section: "Assets", surrogateId: 1 }
{ id: 2, section: "Assets", surrogateId: 2 }
{ id: 1, section: "Firmware", surrogateId: 3 }
{ id: 2, section: "Firmware", surrogateId: 4 }
// ...
```
Then you could still delete individual tables using a surrogate key but you have to make sure to use the correct ID when calling your API. And when creating related models those surrogate keys must either be standardized (by using some conversion format like `assets-1`, `assets-2` etc.) or they must be known to the ORM (e.g. by always creating tables before creating items).

For a practical solution, you could probably extract parts of the reducer into one or more custom functions and call those functions in each model's reducer. The rest of the model classes could be simply copy-pasted for each section (of which you probably don't have all too many). To make other suggestions, I would need to see the exact models and relationships that you have.

**Comment by mbrahimi617** [comment]
I was looking to avoid the whole copy pasting idea, that's why I asked about generalization. But I think I managed to figure out a workaround by creating multiple ORM instances and registering the same ORM models with a higher order reducer.
