### ISSUE TITLE
React example for using selectors

### ISSUE THREAD

**Issue by Bullfrog1234** [redux-orm/redux-orm#421]
Hi Guys, 

I am liking this library but I am struggling to understand how to select data in react components.

If there could be one modification, could the 'selector' section of the documentation be expanded to show a complete example. 

Because the selectors section has lots of small sections of unlinked code, it is hard to understand. Can this be done by showing imports as well. 

Thanks Bullfrog

**Comment by haveyaseen** [comment]
Hi @Bullfrog1234, it's actually all there but it depends on how you want to actually use a selector. Let's first define some selectors and export them.

**selectors.js**
```js
import { createSelector } from "redux-orm";
import orm from "../path/to/orm";

export const authors = createSelector(orm.Author);
export const authorBooks = createSelector(orm.Author.books);
```

In React you have two major ways to use selectors.

1. The `useSelector` hook

```js
import { useSelector } from "react-redux";
import { authors, authorBooks } from "../path/to/selectors";

export const AuthorProfile = (props) => {
  const author = useSelector(state => authors(state, props.authorId));
  const books = useSelector(state => authorBooks(state, props.authorId));
  return (
    <div>{author.name} has written {books.length} books!</div>
  );
};
// Usage: e.g. <AuthorProfile authorId={1} />
```

2. The `mapStateToProps` argument to the `connect` higher-order component (HOC)

```js
import { connect } from "react-redux";
import { authors, authorBooks } from "../path/to/selectors";

const AuthorProfile = (props) => (
  return (
    <div>{props.author.name} has written {props.books.length} books!</div>
  );
);

const mapStateToProps = (state, ownProps) => ({
  author: authors(state, ownProps.authorId),
  books: authorBooks(state, ownProps.authorId),
});

export connect(mapStateToProps)(AuthorProfile);
// Same usage: e.g. <AuthorProfile authorId={1} />
```

This is pretty much all you have to do most of the time. You can of course leave out the second selector argument `authorId` if you want to get all authors or each author's books instead.

I highly recommend the [React-Redux docs](https://react-redux.js.org/) for fully grasping these concepts and other possibilities.

**Comment by Bullfrog1234** [comment]
Thanks @haveyaseen, 

Now I see the mistakes I was making and the confusion that I was having.

Thanks for the amazing library.

Cheers

**Comment by poc7667** [comment]
> Hi @Bullfrog1234, it's actually all there but it depends on how you want to actually use a selector. Let's first define some selectors and export them.
> 
> **selectors.js**
> 
> ```js
> import { createSelector } from "redux-orm";
> import orm from "../path/to/orm";
> 
> export const authors = createSelector(orm.Author);
> export const authorBooks = createSelector(orm.Author.books);
> ```
> 
> In React you have two major ways to use selectors.
> 
> 1. The `useSelector` hook
> 
> ```js
> import { useSelector } from "react-redux";
> import { authors, authorBooks } from "../path/to/selectors";
> 
> export function AuthorProfile(props) {
>   const author = useSelector(state => authors(state, props.authorId));
>   const books = useSelector(state => authorBooks(state, props.authorId));
>   return (
>     <div>{author.name} has written {books.length} books!</div>
>   );
> };
> // Usage: e.g. <AuthorProfile authorId={1} />
> ```
> 
> 1. The `mapStateToProps` argument to the `connect` higher-order component (HOC)
> 
> ```js
> import { connect } from "react-redux";
> import { authors, authorBooks } from "../path/to/selectors";
> 
> function AuthorProfile(props) {
>   return (
>     <div>{props.author.name} has written {props.books.length} books!</div>
>   );
> }
> 
> const mapStateToProps = (state, ownProps) => ({
>   author: authors(state, ownProps.authorId),
>   books: authorBooks(state, ownProps.authorId),
> });
> 
> export connect(mapStateToProps)(AuthorProfile);
> // Same usage: e.g. <AuthorProfile authorId={1} />
> ```
> 
> This is pretty much all you have to do most of the time. You can of course leave out the second selector argument `authorId` if you want to get all authors or each author's books instead.
> 
> I highly recommend the [React-Redux docs](https://react-redux.js.org/) for fully grasping these concepts and other possibilities.


I got **TypeError: Cannot read property 'Article' of undefined** by using your method.

Let me sidetrack this question a little bit.

Is there any more popular ORM library than redux-orm, it's only has few examples on the internet.

# Article.js

	```
	class Article extends Model {
	    static reducer(action, Article, session) {
	        switch (action.type) {
	            case 'load_all':
	                action.payload.forEach(articleData=>{
	                    Article.create(articleData);
	                })
	                return session;
	                break;
	        }
	        return undefined;
	    } 
	}

	Article.modelName = 'Article'
	Article.fields = {
	        id: attr(), // non-relational field for any value; optional but highly recommended
	        name: attr(),
	};

	export default Article;

	```

# orm.js

```
	const orm = new ORM ({
	  stateSelector: state => state.orm,
	});
	orm.register(Article);
```
# ArticleList.js

```
    const articlesSelector = createSelector(orm.Article);
    const ormArticles = useSelector(state => articlesSelector(state, null));

```
