### ISSUE TITLE
QuerySet Delete

### ISSUE THREAD

**Issue by mbrahimi617** [redux-orm/redux-orm#422]
All of my Redux-ORM operations appear to be working aside from deletion. First I construct a session using my ORM instance and pull my Item model from it. Then I retrieve the QuerySet and attempt to delete and I'm getting the error below. Any ideas why?

    Unhandled Rejection (TypeError): Cannot read property 'filter' of undefined

**Comment by haveyaseen** [comment]
Strange. Could you post the complete stack trace please, so we know where `filter` is accessed?

**Comment by mbrahimi617** [comment]
![image](https://user-images.githubusercontent.com/31360324/72078331-e24f9080-32c6-11ea-82aa-c546220b068b.png)

**Comment by haveyaseen** [comment]
> ![image](https://user-images.githubusercontent.com/31360324/72078331-e24f9080-32c6-11ea-82aa-c546220b068b.png)

"4/6 stack frames were collapsed" Mind opening those?

**Comment by mbrahimi617** [comment]
Basically, my react-router reremounts every time it navigates to a page. If I first go to a page, it will execute a fetch action whereupon if I return to that page it will call the action again because the page component has . I've tried removing the deletion and the data is actually duplicated. My idea is to delete the whole QuerySet and populate it again. Maybe my stream of thought is incorrect.

**Comment by mbrahimi617** [comment]
![image](https://user-images.githubusercontent.com/31360324/72078747-acf77280-32c7-11ea-8482-50eb1dec6211.png)

**Comment by haveyaseen** [comment]
It's not finding a model that is referred to by a `fk` field in `Item`.

**Comment by mbrahimi617** [comment]
Oh? So should I fetch the most toplevel model first? For example Item has an FK to Table.

**Comment by haveyaseen** [comment]
It has nothing to do with fetching. The `Table` model is not found in the item's session. If you `console.log` the `session` that you got the Item model from, there likely won't be a `Table`. So `Table` needs to be passed to `orm.register(…)`.

**Comment by mbrahimi617** [comment]
I can assure you that the table is in fact registered:

```js
export const asset = new ORM({

  stateSelector: s => s.asset

});


asset.register(Table);

asset.register(Item);
```

**Comment by mbrahimi617** [comment]
![image](https://user-images.githubusercontent.com/31360324/72082487-3a3dc580-32ce-11ea-907b-da5daf6f36d9.png)

**Comment by haveyaseen** [comment]
Hmm, are you registering the models in two different ORMs? What are the `Table.fields`, `Item.fields`, `session.Table.virtualFields` and `session.Item.virtualFields`? There should be a `fk` or `many` somewhere that's breaking this.

**Comment by mbrahimi617** [comment]
I'm registering them both to the same ORM called asset as you can see. But I'm reusing the models for other parts of my application as well using different ORM instances. Obviously those should be isolated in their own scopes though.

**Comment by mbrahimi617** [comment]
And I don't see a `virtualFields` attribute anywhere.

**Comment by mbrahimi617** [comment]
![image](https://user-images.githubusercontent.com/31360324/72084825-3744d400-32d2-11ea-84f5-aac6a0e06eaa.png)

The Supp and Info models are only registered in other ORM instances. So why do they appear here?

**Comment by mbrahimi617** [comment]
Is registering all models to all the ORM the only solution? For some ORMs, some models are extraneous.
