### ISSUE TITLE
[Question] Is it ok to combine reducers in the orm update to preserve splitted business logic

### ISSUE THREAD

**Issue by zazapeta** [redux-orm/redux-orm#458]
Hello,

I'm discovering this beautiful library. I'm not very fan of the [Model's reducer](https://redux-orm.github.io/redux-orm/basics/reducers#modelreducer) because I like to split [reducers by features](https://github.com/erikras/ducks-modular-redux).

So I ended by doing this : 

```js 
// reducers.js
import { combineReducers } from 'redux';
import { createReducer } from 'redux-orm';

import Auth from '../features/auth/auth.ormReducer';
import orm from '../redux-orm-models';

const reduceReducers = (...reducers) => (state, action) =>
  reducers.reduce((previousState, reducer) => reducer(previousState, action), state);

export default combineReducers({
  orm: createReducer(orm, reduceReducers(Auth)),
  // ... other reducers
});
```
The [updater](https://redux-orm.github.io/redux-orm/api/module_redux#-createreducerorm-updater%E2%87%92-function) is 'reduced' array of reducers.

```js
// auth.ormReducer.js
import { ACTION_TYPES as AuthActionTypes } from './auth.actions';
// NOTE: As this reducer is 'integrated' o the orm reducer, 
// it receive the session and not the entire state -- is it normal ?
export default function authOrmReducer(session, action) {
  const { type, payload } = action;
  const { User } = session;
  switch (type) {
    case AuthActionTypes.LOGIN_SUCCESS:
      User.create(payload);
      break;
    case AuthActionTypes.LOGOUT:
      User.delete();
      break;
  }
  return session;
}
```

I wonder to know your thought about this way to do. Indeed, so the Auth reducer is 'integrated' to the orm reducer, it receive the session and not the whole state -- is it normal ? Can I do this 'safely' or it is crazy and I should avoid this.

Thanks you for your reading and for your help.

**Comment by markerikson** [comment]
Yes, that's fine.  You can split up your reducer logic however you want, including emphasizing Redux-ORM usage in "feature reducers" rather than attaching them to models.  I show some examples of this in [my "Practical Redux" tutorial series](https://blog.isquaredsoftware.com/series/practical-redux).

**Comment by zazapeta** [comment]
Thanks you !
