### ISSUE TITLE
Relationship not updated

### ISSUE THREAD

**Issue by aliehsan90** [redux-orm/redux-orm#460]
The following are my two classes:
```javascript
import { Model, ORM } from "redux-orm";

// One user can have many assignments.
// One assignment can only have one user.
// So its a one-to-many relationship.

class Assignment extends Model {}
Assignment.modelName = 'Assignment';

Assignment.fields = {
    id: attr(),
    description: attr(),
    userId: fk({
        to: 'User',
        as: 'user',
        relatedName: 'assignments'
    })
}

class User extends Model {}
User.modelName = 'User';

User.fields = {
    id: attr(),
    name: attr(),
    email: attr(),
}
```

Then when I load data from server, it loads fine and the `userId` field in `Assignment` establishes relationship between `Assignment` and `User`.
```javascript
assignments.map((assignment) => session.Assignment.upsert(assignment))
users.map((user) => session.User.upsert(user));
```

So when I do `user1.assignments.toModelArray()` it gives me all of the user1's assignments 
and when I do `user2.assignments.toModelArray()` it gives me all of the user2's assignments. 

However say if `assignment1` belonged to `user1` (with id=1) and we want to make it belong to `user2` (with id=2) like so:

```javascript
// Assignment that belonged to user1.
const assignment1Ref = assignment1.ref;
assignment1Ref.userId = 2;
session.Assignment.upsert(assignment1Ref);
```

The assignment should belong to `user2`. So when I do:
```javascript
user2.assignments
```
I should get `assignment1` in `user2.assignments` array however it doesn't contain `assignment1`. And if I do `user1.assignments`, it contains `assignment1`.

Can you please guide me. What am I missing here?

**Comment by samuelcolburn** [comment]
Where are you performing these operations? There should be no need to use `ref` methods if you are inside a reducer, defined in either the model or within a custom reducer. Regardless, when using `ref` objects, I would suggest always cloning them before performing any other actions. Modifying the `ref` object directly may lead to unexpected behavior.

You should be able to do something like:
```javascript
class Assignment extends Model {
  static reducer(action, Assignment, session) {
    let assignment;
    switch (action.type) {
    case 'ASSIGN_USER':
        assignment = Assignment.withId(action.payload.assignmentId);
        assignment.userId = action.payload.userId;
        break;
    }
  }
}
```
Note that this is just using your example with the docs Model Reducer pattern, it has not been tested.

See Docs:
[Model Reducers](https://redux-orm.github.io/redux-orm/basics/reducers)
[Custom Reducer](https://redux-orm.github.io/redux-orm/advanced/custom-reducer)

**Comment by aliehsan90** [comment]
Thanks, another technique that worked for me was to `delete` the Assignment before calling `upsert`.

**Comment by haveyaseen** [comment]
I think the problem here was that you modified the ref directly, which means that Redux-ORM could no longer see that it had to update anything when you called `upsert`. Always use Model classes and objects to modify the databse state or upsert using clones of the objects like this:
```js
const assignment1Ref = assignment1.ref;
session.Assignment.upsert({ ...assignment1Ref, userId: 2 });
```
