### ISSUE TITLE
How to add static function instead of reducer action

### ISSUE THREAD

**Issue by kunaldodiya** [redux-orm/redux-orm#470]
Hi,

I am new and just started learning Redux-ORM, I like Redux but boilerplate are pain, so want to use redux as little as possible

Like in Rematch library, You don't have to specify reducer action at all, you can create action inside rematch model and trigger that

Can we do the same like 

```
class Book extends Model {
   public static modelName = "Book";
   public static observable = {
     loading: false
   }
   public static persist = {
     whitelist: ['*'],
     blacklist:['loading']
   }

   @reducer("CREATE_A_BOOK")
   function addBook(book){
      return this.create(book);
   }

   @reducer("GET_BOOK_BY_ID")
   function bookById(book){
      return this.find(book);
   }

   @reducer("GET_ALL_BOOKS")
   function getAll(){
      return this.all();
   }

   @effect("LOAD_BOOKS") @retry({attempt: 3})
   async function loadBooks(){
    try {
        this.loading = true;
        const {data} = await axios.get("https://www.example.com/books");
        this.createMany(data.books);
        this.loading = false;
        return this.all();
     } catch (e) {
        this.loading = false;
        return e.response;
     }
   }
}
```

now inside component we can directly do

```

import Book from './models';

function App(){
  const dispatch = useDisptach();

   useEffect(() => {
      Book.loadBooks(); OR dispatch({type: "LOAD_BOOKS"})
   }, []);

   return (
      <>
        <TouchableOpacity onPress={() => Book.addBook({id:1, name:"the secret"})}>
            <Text>add book</Text>
         </TouchableOpacity>


         <FlatList 
             data={Book.getAll()} 
             renderItem={({item}) => <Text>{itm.name}</Text>}
          />
      </>
   )
}
```

Sorry if it's too noob

**Comment by markerikson** [comment]
Note that [our official Redux Toolkit library](https://redux-toolkit.js.org) is our recommended approach for writing Redux code overall, and is specifically designed to minimize the "boilerplate" you're referring to.

**Comment by kunaldodiya** [comment]
> Note that [our official Redux Toolkit library](https://redux-toolkit.js.org) is our recommended approach for writing Redux code overall, and is specifically designed to minimize the "boilerplate" you're referring to.

Thanks, I will give it a try

**Comment by kunaldodiya** [comment]
Anyway to separate model from reducer ?

currently model has static reducer method in it but i want to keep reducer function and model separated and call Model.create from reducer only

**Comment by markerikson** [comment]
Create a reducer that takes the `state.entities` section of your state, creates a Redux-ORM session, applies updates, and returns the updated state.  I show how to do this in [my "Practical Redux" tutorial series](https://blog.isquaredsoftware.com/series/practical-redux), although the posts are a couple years old and the Redux-ORM API has changed some since then.
