### ISSUE TITLE
Persistence and Bulk Fetching

### ISSUE THREAD

**Issue by jibberishclient** [redux-orm/redux-orm#472]
What is the optimal way of inserting fetched data on mount with Redux ORM? At the top of my mind, given some type of response data I would do the following:

```
resp.forEach(i => MyModel.create(i));
```

Which to be honest, a model should have bulk features instead of forEach/create like this. Also there should be a way to "set" the data rather than creating because the fetching could happen on a tab switch or a drag-and-reload or on various mounts throughout the application usage in which case duplicate or outdated data may exist. There should also be persistence features.

**Comment by haveyaseen** [comment]
Hi @jibberishclient, for my opinion on bulk features see https://github.com/redux-orm/redux-orm/issues/277#issuecomment-537171698.

[redux-persist](https://github.com/rt2zz/redux-persist) should help with persistence, we have made sure to keep Redux-ORM compatible with it.
