### ISSUE TITLE
Trying to integrate with redux-toolkit

### ISSUE THREAD

**Issue by krunaldodiya** [redux-orm/redux-orm#473]
Hi,

I have created new react-native demo project to test this with redux-toolkit, 

Good Thing is "It's Working"

but need some help regarding,

It is not updating state in react-native-debugger tool only

otherwise it is working fine, no problem at all

Can you please help me get that working :)

https://github.com/kunaldodiya/redux-toolkit-with-redux-orm

**Comment by barnomics** [comment]
Where in your project is it actually using redux-toolkit?  It's not even in the package.json

**Comment by markerikson** [comment]
Yeah, and this isn't the right place to ask for help on that kind of topic.

I'd recommend asking over in the Reactiflux chat channels on Discord:

https://www.reactiflux.com
