### ISSUE TITLE
Error generated when calling upsert()

### ISSUE THREAD

**Issue by jmcpeak** [redux-orm/redux-orm#513]
```
in catch TypeError: Cannot read property '@@_______immutableOpsOwnerID' of undefined
    at canMutate (index.js:31)
    at Object.immutableArrFilter (index.js:368)
    at Object.<anonymous> (_curryN.js:40)
    at Object.filter (_arity.js:21)
    at Table.js:544
    at Array.reduce (<anonymous>)
    at Table.update (Table.js:538)
    at update (Database.js:99)
    at Session.applyUpdate (Session.js:107)
    at SessionBoundModel.update (Model.js:636)
    at Function.upsert (Model.js:377)
    at payerUser.js:18
```

Trying to debug further but the error goes away if I use `create()` instead of `upsert()`.

This model has a foreign key to another table:

```
static get fields() {
    return {
        ...
        payerId: fk(Payer.modelName, 'payerUsers'),
```

If I remove this foreign key the problem goes away as well.
Also, I get the error if the model at the fk has an entry for that id or not.

version: `"redux-orm": "0.16.1"`

**Comment by jmcpeak** [comment]
Here s the line it's failing at:

```
indexMap[attr] = ops.batch.merge(batchToken, _defineProperty({}, value, ops.batch.filter(batchToken, function (rowId) {
```

**Comment by jmcpeak** [comment]
The actual issue is in the here in immutable-ops:

https://github.com/tommikaikkonen/immutable-ops/blob/e202a45d415a382e37c6e74f162b2eb496720502/src/index.js#L31

**Comment by jmcpeak** [comment]
On this line:
https://github.com/redux-orm/redux-orm/blob/b7cd4b37b288054ddb5a371e325da3a19ad70998/src/db/Table.js#L470

My `preValue` at that line is `undefined`, not `null`.
It fails the check and continue's on causing an error downstream.
Should this not be a `isNil()` check? That fixed my problem when I changed it in my local `node_modules` folder.

**Comment by jmcpeak** [comment]
The cause of the problem appears to be that the first time this object was created with an `upsert` the data field for the foreign key `payerId` was `undefined`. The next time `upsert` was called it had a valid key of `1000`. That is what is causing the issue.

**Comment by kpiotr** [comment]
I'm facing the same issue when upgrading from 0.12.4 to 0.16.1. As a workaround I'm setting default values for all fields when creatring models like this:

```
Object.keys(this.fields).reduce((acc, val) => {
      if (this.fields[val] instanceof ManyToMany) {
        acc[val] = [];
      } else {
        acc[val] = null;
      }

      return acc;
    }, {})
```
 However, I'd rather solve this on redux-orm level.

**Comment by haveyaseen** [comment]
@kpiotr reproduced in above PR
