### ISSUE TITLE
Ability to index fields?

### ISSUE THREAD

**Issue by cdelguercio** [redux-orm/redux-orm#88]
I've looked through the docs and the source code a bit and it seems like there isn't a way to index a field in a table. I assume this means that any filter/exclude operations are not particularly fast.

Is this the case, or have I overlooked something?

**Comment by Elijen** [comment]
Yes, indexing is not yet implemented.

I am working on indexing under #78. I have a prototype working, but first tests didn't show any noticeable performance gains. I'll be doing some testing and benchmarking in the next couple days.

**Comment by cdelguercio** [comment]
I'd love to help out with benchmarking/testing. My use case is that I have 20,000-100,000 data points that I pull in from an API and display as a few different graphs. I'd like to be able to chop up the data by foreign key and date range.

**Comment by Elijen** [comment]
Thanks, I will let you know when I push this to my fork. So far I implemented just a simple map index. Using a range for filtering would require a different type of index (btree?). That's planned for later.

**Comment by Elijen** [comment]
I finally found a way how to make the indexes faster, feel free to check my fork:
https://github.com/elijen/redux-orm

The implementation will likely change, but API will probably stay the same. Might still be buggy (no test coverage yet).
